server:
  port: 8099
spring:
  pro

# 对象赋值
person:
  name: CRIOWN
  age: 23
  happy: false
  birth: 2000/10/27
  maps: {key1: value1,k2: v2}
  lists:
    - code
    - music
    - read
  dog:
    name: 修狗
    age: ${random.int}


---
server:
  port: 8081
spring:
  profiles: test


---
server:
  port: 8082
spring:
  profiles: dev
